<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9403" started-at="2019-07-25T02:05:32Z" finished-at="2019-07-25T02:05:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9403" started-at="2019-07-25T02:05:32Z" finished-at="2019-07-25T02:05:41Z">
      <class name="com.upgrade.uitests.UpgradePersonalLoanTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.upgrade.uitests.UpgradePersonalLoanTests@4f7d0008]" name="setUp" is-config="true" duration-ms="4373" started-at="2019-07-25T02:05:32Z" finished-at="2019-07-25T02:05:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test_loanAmount_APR_monthlyPaymentCorrectlyDisplayedAfterLogin(com.upgrade.data.ClientInfo)[pri:0, instance:com.upgrade.uitests.UpgradePersonalLoanTests@4f7d0008]" name="test_loanAmount_APR_monthlyPaymentCorrectlyDisplayedAfterLogin" duration-ms="4823" started-at="2019-07-25T02:05:36Z" data-provider="clientData" finished-at="2019-07-25T02:05:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.upgrade.data.ClientInfo@d2de489]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Affordable Online Personal Loans | Upgrade] but found [Check your rate for a personal loan | Upgrade]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Affordable Online Personal Loans | Upgrade] but found [Check your rate for a personal loan | Upgrade]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.upgrade.uitests.UpgradePersonalLoanTests.test_loanAmount_APR_monthlyPaymentCorrectlyDisplayedAfterLogin(UpgradePersonalLoanTests.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_loanAmount_APR_monthlyPaymentCorrectlyDisplayedAfterLogin -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.upgrade.uitests.UpgradePersonalLoanTests@4f7d0008]" name="afterMethod" is-config="true" duration-ms="175" started-at="2019-07-25T02:05:41Z" finished-at="2019-07-25T02:05:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_loanAmount_APR_monthlyPaymentCorrectlyDisplayedAfterLogin status=FAILURE method=UpgradePersonalLoanTests.test_loanAmount_APR_monthlyPaymentCorrectlyDisplayedAfterLogin(com.upgrade.data.ClientInfo)[pri:0, instance:com.upgrade.uitests.UpgradePersonalLoanTests@4f7d0008] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.upgrade.uitests.UpgradePersonalLoanTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
